### ISSUE TITLE
Definitive edition mods not working

### ISSUE THREAD

**Issue by slappygig** [XPMUser/XPMUser.github.io#15]
Your definitive editions 2 speed mods don't work because I don't see it in effect

**Comment by Ao28th28** [comment]
2015's versions are different than Summer 2016's versions.

**Comment by Ao28th28** [comment]
https://slappygig.github.io/oldprodigy/1-11-0/?mods=WalkSpeed,FastGameSpeed The speed mods are also unusable in your 1.11.0.

**Comment by Ao28th28** [comment]
Definitive Edition Vs. Bannard

**Comment by Ao28th28** [comment]
@slappygig Slappygig.github.io doesn't have all of my versions, but it does have all of daboss7173's versions.

**Comment by XPMUser** [comment]
They work for pde2016 and pde2019.
