### ISSUE TITLE
how i change speed?

### ISSUE THREAD

**Issue by Toonigy** [XPMUser/XPMUser.github.io#21]
How do i change the speed in your definitive edition since you have mods?

**Comment by Ao28th28** [comment]
There's a problem doing it.

**Comment by Ao28th28** [comment]
https://xpmuser.github.io/oldprodigy/oldprodigyde/?mods=WalkSpeed,FastGameSpeed There's a problem getting it to speed up.

**Comment by Ao28th28** [comment]
I dunno
