### ISSUE TITLE
Add pumpkinfest mod

### ISSUE THREAD

**Issue by Toonigy** [XPMUser/XPMUser.github.io#58]
### What would you like to add?

Add a mod that adds pumpkinfest

### Type of suggestion

New Prodigy Definitive Edition or Ultimate Edition feature

### I agree to the following

- [X] By checking this box, I confirm that this issue isn't about adding a new Prodigy version from August 17, 2017, later, or earlier than March 2015.
- [X] By checking this box, I confirm that there are no open issues about this suggestion.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should be using Discord to do that.
- [X] By checking this box, I confirm that I won't ask for any apis or OAuths.
- [X] By checking this box, I confirm that this issue isn't about adding modified versions of later than 2017 or earlier than March 2015's Prodigy versions.
- [X] By checking this box, I confirm that I'm asking for something for only my site (https://xpmuser.github.io/).

**Comment by XPMUser** [comment]
I'll add it if I can.
