### ISSUE TITLE
Add a full screen button in pde1500

### ISSUE THREAD

**Issue by Tongameshacked** [XPMUser/XPMUser.github.io#72]
### What would you like to add?

Add a full screen button

### How would you like this to be implemented? (optional)

A button in settings to change to full screen 

### Type of suggestion

New Prodigy Definitive Edition or Ultimate Edition feature

### I agree to the following

- [X] By checking this box, I confirm that this issue isn't about adding a new Prodigy version from August 17, 2017, later, or earlier than March 2015.
- [X] By checking this box, I confirm that there are no open issues about this suggestion.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug.
- [X] By checking this box, I confirm that I'm not asking for any apis (servers and the real multiplayer mode) or OAuths.
- [X] By checking this box, I confirm that this issue isn't about adding modified versions of later than 2017 or earlier than March 2015's Prodigy versions.
- [X] By checking this box, I confirm that I'm asking for something for only my site (https://xpmuser.github.io/).

**Comment by XPMUser** [comment]
Press F11 or hold Fn and press F11
