### ISSUE TITLE
Store not working

### ISSUE THREAD

**Issue by SplatterMaster** [XPMUser/XPMUser.github.io#73]
### What went wrong?

No clue if you're already working on it or not, but no matter what I try, the store is always unavailable

### Which version?

3.18.5

### How can I reproduce this?

Open the store in any way
![image](https://github.com/user-attachments/assets/8298573b-793c-4c58-9492-03ae372c2cc7)

### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)

![image](https://github.com/user-attachments/assets/02500291-97d2-470b-8a08-5af13086ebac)

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (xpmuser.github.io), and NOT these websites (daboss7173.github.io / oldprodigy.onrender.com)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.
- [X] By checking this box, I confirm that this issue is being used to report an honest problem with an existing feature.

**Comment by SplatterMaster** [comment]
what's the invalid tag for?

**Comment by XPMUser** [comment]
Render will just give me failed jobs and I don't have a credit card.
