### ISSUE TITLE
3-0-0 index.html is nothing but a white screen with no icon

### ISSUE THREAD

**Issue by slappygig** [XPMUser/XPMUser.github.io#8]
What went wrong:
3-0-0 just gave me white screen
How can I replicate this:
Typed in the link, and all I got is a white screen in 3-0-0
Console log output (optional):

**Comment by XPMUser** [comment]
I can't fix 3-0-0 plus the same happened with 1-7-0. I hope Prodigy Education will still have the stuff required to make 3.0.0 again.

**Comment by XPMUser** [comment]
The game.min.js I found, I can't organize the codes.

**Comment by Ao28th28** [comment]
3.0.0 is hard to make.
